### ISSUE TITLE
Error handling examples

### ISSUE THREAD

**Issue by ScratchMyTail** [freshOS/Networking#11]
I was wondering if it were possible for you guys to provide some error handling examples. I.e. handling 401 errors etc.

Thanks for making networking simple.

**Comment by s4cha** [comment]
Hey @ScratchMyTail here is a sample of a `forbidden` `403` error in our App
```swift 
func vote(photoId: String) -> AnyPublisher<Void, Error> {
    network.post("/photos/\(photoId)/vote").mapError { error -> Error in
        if let e = error as? NetworkingError, e.status == .forbidden {
            // do something
        }
        return error
    }.eraseToAnyPublisher()
}
```
Essentially in a `mapError` block, you'd parse the error as a `NetworkingError` and the you have acces to its status.
Hope this helps ;)

**Comment by ScratchMyTail** [comment]
Thanks. @workingDog is doing an excellent job providing fixes in his parse-error branch. I'm testing it out now. So far it looks good. I will comment on those issues as well. 

Hope it's OK that I closed this issue.

**Comment by s4cha** [comment]
@ScratchMyTail Thanks a  ton for the feedback, going to add this to the readme :)
