### ISSUE TITLE
Invalid JSON output in log

### ISSUE THREAD

**Issue by ScratchMyTail** [freshOS/Networking#14]
When using `network.logLevels = .debug` JSON is not valid in the response output. A ";" is added for each new line and square brackets are replaced with round brackets, just to give you some examples.

Would be nice if the output was valid JSON.

**Comment by workingDog** [comment]
to make the logger produce valid JSON, in NetworkingLogger change log(response: URLResponse, data: Data), to:

    func log(response: URLResponse, data: Data) {
        guard logLevels != .off else {
            return
        }
        if let response = response as? HTTPURLResponse {
            logStatusCodeAndURL(response)
        }
        if logLevels == .debug {
            if let json = try? JSONSerialization.jsonObject(with: data, options: .mutableContainers),
               let jsonData = try? JSONSerialization.data(withJSONObject: json, options: .prettyPrinted) {
                print(String(decoding: jsonData, as: UTF8.self))
            }
        }
    }


Perhaps s4cha could put this in the code for us all.

**Comment by workingDog** [comment]
the following would probably be enough most of the time, it depends on the encoding:

        if logLevels == .debug {
            print(String(decoding: data, as: UTF8.self))
        }

**Comment by s4cha** [comment]
Hey guys, really appreciate your efforts to make this tool better. My free time is very limited at the moment but I'll do my best to review your request as soon as possible :)

**Comment by ScratchMyTail** [comment]
I think it's fair to just close this issue know.

**Comment by s4cha** [comment]
-> https://github.com/freshOS/Networking/pull/20 :)
