### ISSUE TITLE
Parsing Error Info

### ISSUE THREAD

**Issue by s4cha** [freshOS/Networking#16]
As reported by @ScratchMyTail
I have another question; is it possible to see where a mapping from JSON to object fails? Currently I'm only getting error 1 and "Unable To Parse Response". It would be great if I could see which parameter was wrong. I have a nested JSON structure with up to 5-6 levels so its quite cumbersome to troubleshoot.

**Comment by workingDog** [comment]
@s4cha,

I've implemented a parsing error system in my Networking fork at:

https://github.com/workingDog/Networking/tree/parse-error

Once the other PR is processed, I could do another PR with this, if acceptable.

**Comment by ScratchMyTail** [comment]
Stupid question; how do I change to use "parse-error" branch in "Swift Package Manager"?

**Comment by workingDog** [comment]
You could try something like this (untested):

     .package(url: "https://github.com/workingDog/Networking", .branch("parse-error"))

I usually use Xcode "Swift Packages" ->  "https://github.com/workingDog/Networking" -> Branch: parse-error

**Comment by ScratchMyTail** [comment]
Finally figured it out. I had to remove it completely first. I selected the project from the Project Navigator -> Swift Packages then added it again. Was able to fill in the branch there.

I have now tested it in a complex structure and it seems to work fine. I would like a more simple or structured error message but if you read it thoroughly you will figure out what caused the error. It is much better than the old "Parsing error" message. I haven't tested the latest pull-request your merged earlier, but I will do it next week.

Good job! Keep it up! 👍

**Comment by s4cha** [comment]
Fantastic @workingDog ! Keep em' coming ! 💯 
I am off for the weekend but will take a look at this next week. Glad to have a working dog onboard !

**Comment by workingDog** [comment]
good to hear from @ScratchMyTail that it is working. When it comes to testing, I'm not very good at all. 
Have a good weekend.

**Comment by ScratchMyTail** [comment]
@workingDog @s4cha Been testing a bit more when I stumbled upon a small "feature-request" or "missing feature". (Or maybe I'm doing something wrong 😄 )
So, when I have for instance this error:

`withError(Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "round", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)))`

I am not able to extract the specific error. In this case my member "round" is of wrong type. I am casting the Error object to Networking.ParsingError but I can't seem to find the content of codingPath/CodingKeys inside it. I have looked inside DecodingError and I think its possible to extract a more specific error. I am only able to output the DebugDescription. I want in this case; stringValue: "round", intValue: nil.

@s4cha Do you think this will be merged and released anytime soon?

**Comment by workingDog** [comment]
In view of @ScratchMyTail comments, I'm currently looking at the ParsingError. I'm beginning to think ParsingError is a mistake and should be scrapped. @s4cha please don't merge the PR yet. I'll investigate a bit more.

**Comment by workingDog** [comment]
Have removed the ParseError and fixed the jsonPayload issue at:

https://github.com/workingDog/Networking/tree/parse-error 

Use the "normal" DecodingError instead.

**Comment by s4cha** [comment]
@workingDog Let me know when this is mergeable :)

**Comment by workingDog** [comment]
Based on @ScratchMyTail testing this issue can now be closed.
