### ISSUE TITLE
NetworkingError jsonPayload == nil

### ISSUE THREAD

**Issue by ScratchMyTail** [freshOS/Networking#19]
I have been trying to throw my JSON data into regular objects. Everytime I try to use jsonPayload on the NetworkingError it is nil. I can see the correct JSON structure being printed in the log. Am I missing something?

``` 
case .failure(let error):
    let netError = error as! NetworkingError
    print("CODE: \(netError.code)")
    print("---> netError.status: \(netError.status.rawValue)" )
    print("---> \(netError.jsonPayload)")```

**Comment by workingDog** [comment]
@ScratchMyTail, I have updated my parse-error branch that should fix the jsonPayload issue.
 
 https://github.com/workingDog/Networking/tree/parse-error
 
Also to fix the Error issues, I have removed the ParseError system. 
Just use DecodingError, as follows:

    case .failure(let error):
                switch error {
                case is DecodingError:
                    let theError = error as! DecodingError
                        print("\n---> failure DecodingError: \(theError.description)")
                        switch theError {
                        case .typeMismatch(let key, let value):
                            print("\n---> typeMismatch key: \(key)  value: \(value)")
                        case .valueNotFound(let key, let value):
                            print("\n---> valueNotFound key: \(key)  value: \(value)")
                        case .keyNotFound(let key, let value):
                            print("\n---> keyNotFound key: \(key)  value: \(value)")
                        case .dataCorrupted(let key):
                            print("\n---> dataCorrupted key: \(key)")
                        default:
                            print("\n---> default error: \(theError.localizedDescription)")
                        }

                case is NetworkingError:
                    print("\n----> failure NetworkingError: \(error.localizedDescription)")
                    let netError = error as! NetworkingError
                    print("\n----> CODE: \(netError.code)")
                    print("\n----> netError.status: \(netError.status.rawValue)" )
                    print("\n----> \(netError.jsonPayload) \n")
                    if let jsonData = try? JSONSerialization.data(withJSONObject: netError.jsonPayload, options: .prettyPrinted) {
                        print(String(decoding: jsonData, as: UTF8.self))
                    }

                default:
                    print("\n----> failure error: \(error.localizedDescription)")
                }
    
Let me know if this works, if so, I'll do another PR.

**Comment by ScratchMyTail** [comment]
@workingDog jsonPayload issue seems to be fixed in your latest parse-error branch. Been testing it all day. I think you can close this issue now. I would also like to recognise that the ParsingError/DecodingError is also working well now. 

Thanks for your great effort. Hopefully we can get all these fixes merged into the main repo and into a new version soon. (@s4cha )

**Comment by workingDog** [comment]
Thanks for testing things out. Agree, this can be closed now.
