### ISSUE TITLE
Documentation lacks examples using Codable structs

### ISSUE THREAD

**Issue by djrobby** [freshOS/Networking#2]
I would really like to use your library in my current project but I'm having a real hard time getting POST, PUT and DELETE requests to work with Codable structs. Your documentation, including tests, only showcase rather simple examples that use strings as params. It would be nice if you could include addtional examples utilizing Codable structs. Thanks!

**Comment by s4cha** [comment]
Hi @djrobby, indeed the examples in the tests are quite succinct. For and example in a real Appstore App you could check out the code of this fully open-source App :https://github.com/EuroScorer/EuroScorer-iOS
especially https://github.com/EuroScorer/EuroScorer-iOS/blob/master/EuroScorer/Firebase/FirebaseModels.swift and https://github.com/EuroScorer/EuroScorer-iOS/blob/master/EuroScorer/Firebase/FirebaseImplementation.swift

The particularity in this example is that Codable Models have been hidden behind a protocol for cleanness sake but you don't have to go to this level of abstraction if you don't want to.

Let me know if that helps :)

**Comment by s4cha** [comment]
@djrobby Did that help?

**Comment by djrobby** [comment]
Yes, all set! Sorry, I forgot to mark the issue closed. done!
