### ISSUE TITLE
Support for watchOS

### ISSUE THREAD

**Issue by fordee** [freshOS/Networking#25]
Can you modify the Package.swift to allow support for watchOS? Something like this:

import PackageDescription

let package = Package(
    name: "Networking",
    platforms: [.iOS(.v13), .macOS(.v10_15), .watchOS(.v6)],
    products: [.library(name: "Networking", targets: ["Networking"])],
    targets: [
        .target(name: "Networking"),
        .testTarget(name: "NetworkingTests", dependencies: ["Networking"])
    ]
)

**Comment by s4cha** [comment]
@fordee this is a great idea! This should be a transparent change so I'm putting it for next version (later today) 0.3.3
