### ISSUE TITLE
Change parameter encoding

### ISSUE THREAD

**Issue by summongr** [freshOS/Networking#28]
I create a networking client as:

`let client = NetworkingClient(baseURL: "a_valid_url")`

and then I use it to make calls to the server. Some of the calls on the server are `urlEncoded` which is the default when creating the `NetworkingClient` but others are `json` encoded. How can I change the `ParameterEncoding` per request on the `NetworkingClient`? Also, is there any news about #24 ?

Thanks!

**Comment by workingDog** [comment]
before you send a request you can set the parameter encoding like this:

    // set the encoding to json
    client.parameterEncoding = ParameterEncoding.json

See also the README (of my fork).
