### ISSUE TITLE
Support for targets below iOS 13.0 using something like RxSwift

### ISSUE THREAD

**Issue by balecrim** [freshOS/Networking#3]
Would a PR adding support for targets below iOS 13.0 using another reactive programming library be accepted? I am willing to do the actual work of implementing it and coordinating with you guys on it!

Thanks!

**Comment by s4cha** [comment]
Hi @bernardowilson, While I think this is a very good idea adoption-wise, I think this would complicate the dependencies.
What I suggest is that you could fork the repo to issue an RX-compatible version & I would happily link it in the readme for our pre iOS13 friends. Would that work for you?

**Comment by bernardowilson** [comment]
That sounds great! Will fork it and once I have a something useable I'll give you a heads up!

**Comment by s4cha** [comment]
@bernardowilson Amazing! I was thinking we could even use a dedicated branch for that :)

**Comment by s4cha** [comment]
Closing this for now, don't hesitate to ping if something new comes up.
