### ISSUE TITLE
Not Parsing Array, Giving Empty Array in response

### ISSUE THREAD

**Issue by auedbaki** [freshOS/Networking#34]
Response in Json : Any Works, but in [Post] not working result in [] empty array

extension ArrowParsable where Self: NetworkingJSONDecodable {

    public static func decode(_ json: Any) throws -> Self {
        var t: Self = Self()
        if let arrowJSON = JSON(json) {
            t.deserialize(arrowJSON)
        }
        return t
    }
}

struct Post: Decodable {
    var id: Int = 0
    var modified: String = ""
    var title: String = ""
    var link: String = ""
    var featured_img: String = ""
    var author_name: String = ""
    var post_views: Int = 0
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case modified = "modified"
        case title = "title"
        case link = "link"
        case featured_img = "featured_img"
        case author_name = "author_name"
        case post_views = "post_views"
    }
}

extension Post: NetworkingJSONDecodable {}

 self.api.fetchPost(page: 1)
            .mapError({ (error) -> Error in
                    print(error)
                    return error
                })
            .sink(receiveCompletion: { completion in

                switch completion {
                    case .finished:
                        print("Request FInished")
                        break
                    case .failure(let error):
                        print(error)

                }

            }) { (response: [Post]) in

print(response) // gives []
            }.store(in: &cancellables)

**Comment by s4cha** [comment]
@auedbaki Are you still experiencing the issue? Could you please provide a sample project? this is impossible to debug with this few information.

**Comment by auedbaki** [comment]
This issue was because of extra/incorrect field in struct which either not in json data or may be missing in json. Please add in documentation as important point else modify code to ignore these checks.
