### ISSUE TITLE
Multipart uploads are limited to only one multipart section

### ISSUE THREAD

**Issue by jeffbarg** [freshOS/Networking#4]
There seem to be two limitations of the Multipart calls in this Networking library.

1. It looks like when using the multipart data in a request, the params get encoded into the URL. [^1]  This doesn't seem like standard behavior, I think it'd be more intuitive for the params to be encoded as additional multiparts (this is how HTML forms would handle it). [^2] [^3]

2. It looks like there's only support for one Multipart data object per request. It would be handy if the API could support multiple file uploads! [^4]

[^1]: https://github.com/freshOS/Networking/blob/master/Sources/Networking/NetworkingRequest.swift#L123-L125
[^2]: https://ec.haxx.se/http/http-multipart
[^3]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
[^4]: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by s4cha** [comment]
@jeffbarg First thank you for taking the time to post your analysis here, this is very appreciated. Both points are highly relevant and definitely things we need on the short term roadmap.
