### ISSUE TITLE
Cannot find library in Cocoapods

### ISSUE THREAD

**Issue by samuelowino** [freshOS/Networking#41]
I am using Cocoapods for dep management. Is it possible to just use Cocoapods and not swift dep manager ? I can't find the package on the Cocoapods site. https://cocoapods.org/

Thanks!

**Comment by s4cha** [comment]
@samuelowino, we don't support Cocoapods and I am not planing to support it. I think Swift Package Manager should be the preferred package management from now forward. Is there a specific reason preventing you from making the change?

**Comment by samuelowino** [comment]
Hey, @s4cha thanks for replying. Not really, I started my project with Cocoapods but for this reason, I moved to swift package manager. I think it's totally fine if you have chosen not to support it.

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen an issue if needed :)
