### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by elijah-rappaport** [freshOS/Networking#42]
There are two naming issues I've found...

NetworkingLogLevels ==> NetworkingLogLevel
- This should not be a plural. It is an enum defining the particular log level.
REFERENCE
https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html
"Give enumeration types singular rather than plural names, so that they read as self-evident"

HTTPVerb ==> HTTPMethod
- The standard name for this is "method" not "verb"
REFERENCE
https://www.rfc-editor.org/rfc/rfc7231
https://stackoverflow.com/questions/49907027/why-http-methods-are-also-called-verbs

**Comment by s4cha** [comment]
@elijah-rappaport very nice catch ! Do you want to issue a PR or do you prefer I make the changes myself ?

**Comment by elijah-rappaport** [comment]
@s4cha Thanks. I created a PR for these. https://github.com/freshOS/Networking/pull/43
Thanks for creating this great package!

**Comment by s4cha** [comment]
Thanks a ton for making it better for everyone else @elijah-rappaport. This is now live in 1.0.0 :)

**Comment by s4cha** [comment]
Closing this as you solved it.
