### ISSUE TITLE
Timeout setting

### ISSUE THREAD

**Issue by workingDog** [freshOS/Networking#9]
great project, thank you.

Is there a way to configure the client or request timeout?

**Comment by s4cha** [comment]
Hi @workingDog unfortunately, timeout is not yet available in the public api, but it is supported in the underlying `NetworkingRequest`, so I guess you could use a helper like the following: 
```swift
extension NetworkingClient {
    func request(_ httpVerb: HTTPVerb, _ route: String, params: Params = Params(), timeout: TimeInterval? = nil) -> NetworkingRequest {
        let req = NetworkingRequest()
        req.baseURL = baseURL
        req.logLevels = logLevels
        req.headers = headers
        req.httpVerb = httpVerb
        req.route = route
        req.params = params
        req.parameterEncoding = parameterEncoding
        if let t = timeout {
            req.timeout = t
        }
        return req
    }

    func foo() -> AnyPublisher<Data, Error> {
        request(.get, "/", timeout: 1500).publisher()
    }
}
```
Would you like to configure a timeout app-wide or on a call by call basis?

**Comment by workingDog** [comment]
thanks for your reply, at first it looked like a good approach to implement the timeout.
However this does not work, because apart from params, all other vars including timeout are not visible, they are not public.

My particular need at the moment is for a system wide timeout.

Currently, if there is no internet connection for example, it takes at least 60 seconds for the "error" to show up.

**Comment by s4cha** [comment]
Closing this as you added timeout 👍
